export const researchStudies = [
  {
    slug: "symbolic-country-of-origin-cues",
    type: "Master’s Thesis",
    field: "Consumer Behavior & International Marketing",
    title: "Strategic Use of Symbolic Country of Origin Cues to Enhance Consumer Acceptance of Foreign Products: Evidence from Chinese Tea Packaging",
    description: "Experimental consumer research investigating whether symbolic country-of-origin cues—specifically Chinese language characters on product packaging—influence consumers’ perceived product quality and purchase intention. The research also examines perceived product quality as a mediating mechanism and consumer ethnocentrism and sustainability concern as moderating factors. It further introduces the Consumer Cultural Cache (CCC) Framework to explain how culturally embedded knowledge and associations can shape consumer responses to symbolic marketing cues.",
    method: "Quantitative between-subjects experimental research using fictional Chinese tea packaging, where explicit country-of-origin information was held constant while the presence of Chinese characters was manipulated. The study collected 151 valid responses from tea consumers living in Germany through Qualtrics. Data were analyzed in R using independent-samples t-tests, reliability and correlation analysis, regression analysis, mediation analysis, and moderation analysis.",
    topics: ["Consumer Behavior", "International Marketing", "Country-of-Origin Effects", "Symbolic COO Cues", "Packaging Design", "Perceived Product Quality", "Purchase Intention", "Consumer Ethnocentrism", "Sustainability Concern", "Consumer Cultural Cache (CCC) Framework", "Experimental Research"],
    tools: ["Qualtrics","R"],
    sample: "151 tea consumers living in Germany",
    image: "/research-master-packaging.png",
    imageAlt: "Experimental and control Chinese tea packages used to test symbolic country-of-origin cues",
    imageCaption: "Experimental stimulus · Chinese characters vs. Latin alphabet packaging",
    gallery: [
      { src: "/research-master-conceptual.png", alt: "Consumer Cultural Cache conceptual framework", caption: "Consumer Cultural Cache framework" },
      { src: "/research-master-treatment-effect.png", alt: "Violin plot comparing perceived product quality across packaging conditions", caption: "Packaging treatment effect" },
      { src: "/research-master-mediation.png", alt: "Mediation model through perceived product quality", caption: "Perceived-quality mediation model" },
      { src: "/research-master-ethnocentrism.png", alt: "Moderation effect of consumer ethnocentrism", caption: "Consumer ethnocentrism moderation" },
      { src: "/research-master-sustainability.png", alt: "Moderation effect of sustainability concern", caption: "Sustainability-concern moderation" },
    ],
    pdf: "/symbolic-country-of-origin-cues-chinese-tea-packaging.pdf",
    pages: 101,
  },
  {
    slug: "ai-regulation-public-trust",
    type: "Research Project",
    field: "AI Regulation & Human-AI Interaction",
    title: "Does AI Regulation Increase Public Trust? Risk Perception under the EU AI Act",
    description: "Experimental research investigating how EU AI Act disclosure influences perceived risk, trust in AI systems, and adoption intention among Generation Z users. The study examines whether regulatory transparency strengthens public confidence in AI or instead acts as a risk signal that increases perceived risk and reduces trust.",
    method: "Quantitative between-subjects experimental study with 30 Generation Z participants, randomly assigned to control and EU AI Act disclosure conditions. Data were collected through Qualtrics and analyzed in R, applying descriptive statistics, reliability analysis, independent-samples t-tests, correlation analysis, linear regression, and bootstrap mediation analysis.",
    topics: ["EU AI Act", "AI Regulation", "Trust in AI", "Perceived Risk", "Technology Adoption", "Human-AI Interaction", "Generation Z", "Experimental Research", "Mediation Analysis"],
    tools: ["Qualtrics", "R"],
    sample: "30 Generation Z participants",
    image: "/research-ai-act-stimulus.png",
    imageAlt: "AI chatbot interface displaying an EU AI Act disclosure banner",
    imageCaption: "Treatment condition · EU AI Act disclosure interface",
    gallery: [
      { src: "/research-ai-conceptual-framework.png", alt: "Conceptual framework linking EU AI Act disclosure, perceived risk, trust in AI, and adoption intention", caption: "Conceptual research framework" },
      { src: "/research-ai-risk-comparison.png", alt: "Violin plot comparing perceived risk for control and EU AI Act disclosure groups", caption: "Perceived risk by experimental condition" },
      { src: "/research-ai-mediation-model.png", alt: "Mediation model showing the relationships between EU AI Act disclosure, perceived risk, trust, and adoption intention", caption: "Final mediation model" },
    ],
    pdf: "/does-ai-regulation-increase-public-trust.pdf",
    pages: 40,
  },
  {
    slug: "stock-market-participation-undergraduates",
    type: "Bachelor’s Thesis",
    field: "Finance & Investor Behavior",
    title: "The Determinants of Stock Market Participation of Undergraduates",
    description: "Quantitative research investigating the factors influencing undergraduate participation in the Colombo Stock Exchange, focusing on stock-market awareness, income, and access to the internet as determinants of investment participation.",
    method: "Quantitative survey research with 100 undergraduate participants from the Faculty of Management Studies and Commerce, University of Sri Jayewardenepura. The study used questionnaire data and analyzed it in STATA, applying descriptive statistics, Cronbach’s alpha, correlation analysis, Probit regression, and marginal-effects analysis.",
    topics: ["Stock Market Participation", "Investor Behavior", "Financial Literacy", "Investment Decisions", "Colombo Stock Exchange", "Quantitative Research", "Probit Regression"],
    tools: ["Questionnaire", "STATA"],
    sample: "100 undergraduate participants",
    image: "/research-stock-market-framework.png",
    imageAlt: "Conceptual framework connecting awareness, income, and internet access to undergraduate stock-market participation",
    imageCaption: "Conceptual framework · Determinants of stock-market participation",
    gallery: [
      { src: "/research-bachelor-sample.png", alt: "Charts showing stock ownership and broker registration among participants", caption: "Participation and broker registration" },
      { src: "/research-bachelor-probit.png", alt: "Probit regression results for broker registration", caption: "Probit regression estimates" },
      { src: "/research-bachelor-marginal-stock.png", alt: "Marginal effects results for undergraduate stock availability", caption: "Marginal-effects analysis" },
    ],
    pdf: "/determinants-stock-market-participation-undergraduates.pdf",
    pages: 44,
  },
];

export function getResearchStudy(slug) {
  return researchStudies.find((study) => study.slug === slug);
}
